/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    articles: Article;
    entities: Entity;
    projects: Project;
    initiatives: Initiative;
    downloads: Download;
    claims: Claim;
    'evidence-sources': EvidenceSource;
    assets: Asset;
    'inquiry-routes': InquiryRoute;
    inquiries: Inquiry;
    'delivery-attempts': DeliveryAttempt;
    'newsletter-subscriptions': NewsletterSubscription;
    redirects: Redirect;
    'rate-limit-buckets': RateLimitBucket;
    'audit-events': AuditEvent;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    entities: EntitiesSelect<false> | EntitiesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    initiatives: InitiativesSelect<false> | InitiativesSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    'evidence-sources': EvidenceSourcesSelect<false> | EvidenceSourcesSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'inquiry-routes': InquiryRoutesSelect<false> | InquiryRoutesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'delivery-attempts': DeliveryAttemptsSelect<false> | DeliveryAttemptsSelect<true>;
    'newsletter-subscriptions': NewsletterSubscriptionsSelect<false> | NewsletterSubscriptionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'rate-limit-buckets': RateLimitBucketsSelect<false> | RateLimitBucketsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Stable PAGE ID from the approved information architecture. Changing this requires a change request.
   */
  pageId:
    | 'HOME'
    | 'ABOUT'
    | 'ENTERPRISE'
    | 'IDEAS'
    | 'CULTURE'
    | 'IMPACT'
    | 'MEDIA'
    | 'CONNECT'
    | 'ARTICLE'
    | 'ENTITY'
    | 'PROJECT'
    | 'INITIATIVE'
    | 'SEARCH'
    | 'PRIVACY'
    | 'TERMS'
    | 'ACCESSIBILITY';
  /**
   * Proposed public path. Frozen into the SEO register before launch; changes require a redirect record.
   */
  path: string;
  /**
   * Baseline purpose for this page. Judge every content decision against it.
   */
  purpose?: string | null;
  /**
   * Approved modular content. Each module carries its own MOD ID and evidence links.
   */
  modules?:
    | (HeroBlock | RichTextBlock | ProofBlock | TimelineBlock | CardGridBlock | CtaBlock | NewsletterBlock)[]
    | null;
  primaryCta?: {
    /**
     * Stable CTA ID, e.g. CTA-HOME-PRIMARY.
     */
    ctaId?: string | null;
    label?: string | null;
    destinationType?: ('internal' | 'inquiry' | 'external' | 'download' | 'subscribe') | null;
    /**
     * Path, route ID or absolute official URL.
     */
    destination?: string | null;
  };
  seo?: {
    /**
     * SEO record ID, e.g. SEO-HOME.
     */
    seoId?: string | null;
    /**
     * Unique page title. Required before an indexable page can be accepted.
     */
    title?: string | null;
    /**
     * Unique meta description.
     */
    description?: string | null;
    /**
     * Exclude from indexation. Forced on for search results and any non-production origin regardless of this value.
     */
    noindex?: boolean | null;
    /**
     * Rights-cleared 1200x630 social image. Subject to the same asset gate.
     */
    ogImage?: (string | null) | Asset;
  };
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  /**
   * Accountable role for this record. Roles, not named individuals — names are a G0 dependency.
   */
  ownerRole: string;
  /**
   * Traceability notes: source document, change request ID, or the reason a module deviates.
   */
  baselineNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Stable MOD ID. Traces this module to the copy deck, CTA and QA records.
   */
  moduleId:
    | 'MOD-HOME-HERO'
    | 'MOD-HOME-KYYBA-FLAGSHIP'
    | 'MOD-HOME-LEADERSHIP-JOURNEY'
    | 'MOD-HOME-SELECTED-ENTERPRISE'
    | 'MOD-HOME-SELECTED-IDEAS'
    | 'MOD-HOME-SELECTED-CULTURE'
    | 'MOD-HOME-SELECTED-IMPACT'
    | 'MOD-HOME-MEDIA-CREDIBILITY'
    | 'MOD-HOME-FINAL-CTA'
    | 'MOD-ABOUT-BIO'
    | 'MOD-ABOUT-TIMELINE'
    | 'MOD-ABOUT-PRINCIPLES'
    | 'MOD-ABOUT-RECOGNITION'
    | 'MOD-ABOUT-HUMAN-CONTEXT'
    | 'MOD-ABOUT-ENTERPRISE-BRIDGE'
    | 'MOD-ENTERPRISE-KYYBA-FLAGSHIP'
    | 'MOD-ENTERPRISE-APPROACH'
    | 'MOD-ENTERPRISE-PORTFOLIO'
    | 'MOD-ENTERPRISE-ENTITY-ROUTES'
    | 'MOD-ENTERPRISE-QUALIFICATION'
    | 'MOD-IDEAS-FEATURED'
    | 'MOD-IDEAS-TOPIC-FILTERS'
    | 'MOD-IDEAS-FRAMEWORKS'
    | 'MOD-IDEAS-MIND-TRAP'
    | 'MOD-IDEAS-NEWSLETTER'
    | 'MOD-CULTURE-SELECTED-WORK'
    | 'MOD-CULTURE-PROJECT-CARDS'
    | 'MOD-CULTURE-ROLE-CREDIT'
    | 'MOD-CULTURE-OFFICIAL-MEDIA'
    | 'MOD-CULTURE-COLLABORATION'
    | 'MOD-IMPACT-FOCUS-AREAS'
    | 'MOD-IMPACT-INITIATIVES'
    | 'MOD-IMPACT-EVIDENCE'
    | 'MOD-IMPACT-PARTNERS'
    | 'MOD-IMPACT-GEOGRAPHY'
    | 'MOD-IMPACT-PARTICIPATION'
    | 'MOD-MEDIA-TOPICS'
    | 'MOD-MEDIA-BIOS'
    | 'MOD-MEDIA-SPEAKER-REEL'
    | 'MOD-MEDIA-CLIPS'
    | 'MOD-MEDIA-RECOGNITION'
    | 'MOD-MEDIA-PRESS-KIT'
    | 'MOD-MEDIA-INQUIRY-ROUTES'
    | 'MOD-CONNECT-INTENT-SELECTOR'
    | 'MOD-CONNECT-ROUTE-FORM'
    | 'MOD-CONNECT-PRIVACY-NOTICE'
    | 'MOD-CONNECT-ACKNOWLEDGEMENT'
    | 'MOD-ARTICLE-BODY'
    | 'MOD-ARTICLE-CONTEXT'
    | 'MOD-ARTICLE-RELATED'
    | 'MOD-ARTICLE-SUBSCRIBE'
    | 'MOD-ENTITY-CONTEXT'
    | 'MOD-ENTITY-STATUS'
    | 'MOD-ENTITY-EVIDENCE'
    | 'MOD-ENTITY-OFFICIAL'
    | 'MOD-ENTITY-RELATED'
    | 'MOD-PROJECT-CONTEXT'
    | 'MOD-PROJECT-CREDITS'
    | 'MOD-PROJECT-MEDIA'
    | 'MOD-PROJECT-OFFICIAL'
    | 'MOD-PROJECT-RELATED'
    | 'MOD-INITIATIVE-PURPOSE'
    | 'MOD-INITIATIVE-PARTNERS'
    | 'MOD-INITIATIVE-OUTCOMES'
    | 'MOD-INITIATIVE-PARTICIPATE'
    | 'MOD-INITIATIVE-RELATED'
    | 'MOD-SEARCH-INPUT'
    | 'MOD-SEARCH-RESULTS'
    | 'MOD-SEARCH-EMPTY'
    | 'MOD-PRIVACY-POLICY'
    | 'MOD-PRIVACY-CONTACT'
    | 'MOD-TERMS-POLICY'
    | 'MOD-ACCESSIBILITY-COMMITMENT'
    | 'MOD-ACCESSIBILITY-LIMITS'
    | 'MOD-ACCESSIBILITY-ASSISTANCE';
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  /**
   * Positioning line, e.g. Executive Chairman | Enterprise Builder | Investor | Producer.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Master statement or page promise. Material claims must be linked above.
   */
  statement?: string | null;
  image?: (string | null) | Asset;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Claim lifecycle: draft wording, assign owner/reviewer, attach source, approve exact wording and review date, link to modules, publish only when Ready, reverify on schedule.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: string;
  /**
   * Stable claim ID, e.g. CLAIM-003.
   */
  claimId: string;
  /**
   * Step 1 — the exact claim as drafted, including its qualifier and scope.
   */
  exactWording: string;
  /**
   * Scope/qualifier: region, category, period, definition.
   */
  qualifier?: string | null;
  riskLevel: 'material' | 'descriptive';
  /**
   * Step 2 — role accountable for verification.
   */
  verificationOwnerRole: string;
  /**
   * Step 2 — role accountable for risk review.
   */
  riskReviewerRole: string;
  /**
   * Step 3 — source records and evidence strength. A claim with no source can never reach Ready.
   */
  sources?: (string | EvidenceSource)[] | null;
  status: 'blocked' | 'in-verification' | 'ready' | 'withdrawn';
  /**
   * Step 4 — the exact wording approved for public use. Published copy must match this verbatim.
   */
  approvedWording?: string | null;
  approvalDate?: string | null;
  /**
   * Step 7 — scheduled reverification date. Once passed, dependent content is unpublished by the re-check sweep.
   */
  reviewDate?: string | null;
  /**
   * What exactly is missing, and which role owns supplying it.
   */
  blockingReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-sources".
 */
export interface EvidenceSource {
  id: string;
  title: string;
  sourceType:
    | 'corporate-record'
    | 'org-record'
    | 'contract'
    | 'credit-record'
    | 'hr-report'
    | 'platform-evidence'
    | 'filing'
    | 'outcome-methodology'
    | 'third-party';
  strength: 'authoritative' | 'supporting' | 'weak';
  /**
   * Date the source itself carries. Undated sources cannot support a dated claim.
   */
  dated?: string | null;
  /**
   * Where the record is held. Store the pointer, not confidential contents.
   */
  reference?: string | null;
  notes?: string | null;
  /**
   * Withdrawn sources no longer support their claims; the re-check sweep will unpublish dependent content.
   */
  withdrawn?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  /**
   * Stable asset ID, e.g. AST-015.
   */
  assetId: string;
  /**
   * Alt text. Required unless the asset is marked decorative — the gate enforces this.
   */
  alt?: string | null;
  /**
   * Decorative assets are exposed to assistive technology as empty alt.
   */
  decorative?: boolean | null;
  rightsStatus: 'unverified' | 'requested' | 'cleared' | 'refused';
  /**
   * Where the file came from: photographer, distributor, licence reference.
   */
  source?: string | null;
  /**
   * Exactly what this licence permits. Usage beyond this is a rights breach.
   */
  permittedUsage?: string | null;
  /**
   * Licence expiry. Once passed, dependent content is unpublished by the re-check sweep.
   */
  rightsExpiry?: string | null;
  creditRequired?: boolean | null;
  credit?: string | null;
  /**
   * Set when identifiable people appear and a signed release is needed.
   */
  releaseRequired?: boolean | null;
  releaseOnFile?: boolean | null;
  /**
   * Captions or transcript reference. Required for video and audio (FR-MEDIA-01).
   */
  captionsOrTranscript?: string | null;
  version?: string | null;
  /**
   * Clearly identified development placeholder. Placeholders must never enter public release.
   */
  developmentPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    social?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Stable MOD ID. Traces this module to the copy deck, CTA and QA records.
   */
  moduleId:
    | 'MOD-HOME-HERO'
    | 'MOD-HOME-KYYBA-FLAGSHIP'
    | 'MOD-HOME-LEADERSHIP-JOURNEY'
    | 'MOD-HOME-SELECTED-ENTERPRISE'
    | 'MOD-HOME-SELECTED-IDEAS'
    | 'MOD-HOME-SELECTED-CULTURE'
    | 'MOD-HOME-SELECTED-IMPACT'
    | 'MOD-HOME-MEDIA-CREDIBILITY'
    | 'MOD-HOME-FINAL-CTA'
    | 'MOD-ABOUT-BIO'
    | 'MOD-ABOUT-TIMELINE'
    | 'MOD-ABOUT-PRINCIPLES'
    | 'MOD-ABOUT-RECOGNITION'
    | 'MOD-ABOUT-HUMAN-CONTEXT'
    | 'MOD-ABOUT-ENTERPRISE-BRIDGE'
    | 'MOD-ENTERPRISE-KYYBA-FLAGSHIP'
    | 'MOD-ENTERPRISE-APPROACH'
    | 'MOD-ENTERPRISE-PORTFOLIO'
    | 'MOD-ENTERPRISE-ENTITY-ROUTES'
    | 'MOD-ENTERPRISE-QUALIFICATION'
    | 'MOD-IDEAS-FEATURED'
    | 'MOD-IDEAS-TOPIC-FILTERS'
    | 'MOD-IDEAS-FRAMEWORKS'
    | 'MOD-IDEAS-MIND-TRAP'
    | 'MOD-IDEAS-NEWSLETTER'
    | 'MOD-CULTURE-SELECTED-WORK'
    | 'MOD-CULTURE-PROJECT-CARDS'
    | 'MOD-CULTURE-ROLE-CREDIT'
    | 'MOD-CULTURE-OFFICIAL-MEDIA'
    | 'MOD-CULTURE-COLLABORATION'
    | 'MOD-IMPACT-FOCUS-AREAS'
    | 'MOD-IMPACT-INITIATIVES'
    | 'MOD-IMPACT-EVIDENCE'
    | 'MOD-IMPACT-PARTNERS'
    | 'MOD-IMPACT-GEOGRAPHY'
    | 'MOD-IMPACT-PARTICIPATION'
    | 'MOD-MEDIA-TOPICS'
    | 'MOD-MEDIA-BIOS'
    | 'MOD-MEDIA-SPEAKER-REEL'
    | 'MOD-MEDIA-CLIPS'
    | 'MOD-MEDIA-RECOGNITION'
    | 'MOD-MEDIA-PRESS-KIT'
    | 'MOD-MEDIA-INQUIRY-ROUTES'
    | 'MOD-CONNECT-INTENT-SELECTOR'
    | 'MOD-CONNECT-ROUTE-FORM'
    | 'MOD-CONNECT-PRIVACY-NOTICE'
    | 'MOD-CONNECT-ACKNOWLEDGEMENT'
    | 'MOD-ARTICLE-BODY'
    | 'MOD-ARTICLE-CONTEXT'
    | 'MOD-ARTICLE-RELATED'
    | 'MOD-ARTICLE-SUBSCRIBE'
    | 'MOD-ENTITY-CONTEXT'
    | 'MOD-ENTITY-STATUS'
    | 'MOD-ENTITY-EVIDENCE'
    | 'MOD-ENTITY-OFFICIAL'
    | 'MOD-ENTITY-RELATED'
    | 'MOD-PROJECT-CONTEXT'
    | 'MOD-PROJECT-CREDITS'
    | 'MOD-PROJECT-MEDIA'
    | 'MOD-PROJECT-OFFICIAL'
    | 'MOD-PROJECT-RELATED'
    | 'MOD-INITIATIVE-PURPOSE'
    | 'MOD-INITIATIVE-PARTNERS'
    | 'MOD-INITIATIVE-OUTCOMES'
    | 'MOD-INITIATIVE-PARTICIPATE'
    | 'MOD-INITIATIVE-RELATED'
    | 'MOD-SEARCH-INPUT'
    | 'MOD-SEARCH-RESULTS'
    | 'MOD-SEARCH-EMPTY'
    | 'MOD-PRIVACY-POLICY'
    | 'MOD-PRIVACY-CONTACT'
    | 'MOD-TERMS-POLICY'
    | 'MOD-ACCESSIBILITY-COMMITMENT'
    | 'MOD-ACCESSIBILITY-LIMITS'
    | 'MOD-ACCESSIBILITY-ASSISTANCE';
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProofBlock".
 */
export interface ProofBlock {
  /**
   * Stable MOD ID. Traces this module to the copy deck, CTA and QA records.
   */
  moduleId:
    | 'MOD-HOME-HERO'
    | 'MOD-HOME-KYYBA-FLAGSHIP'
    | 'MOD-HOME-LEADERSHIP-JOURNEY'
    | 'MOD-HOME-SELECTED-ENTERPRISE'
    | 'MOD-HOME-SELECTED-IDEAS'
    | 'MOD-HOME-SELECTED-CULTURE'
    | 'MOD-HOME-SELECTED-IMPACT'
    | 'MOD-HOME-MEDIA-CREDIBILITY'
    | 'MOD-HOME-FINAL-CTA'
    | 'MOD-ABOUT-BIO'
    | 'MOD-ABOUT-TIMELINE'
    | 'MOD-ABOUT-PRINCIPLES'
    | 'MOD-ABOUT-RECOGNITION'
    | 'MOD-ABOUT-HUMAN-CONTEXT'
    | 'MOD-ABOUT-ENTERPRISE-BRIDGE'
    | 'MOD-ENTERPRISE-KYYBA-FLAGSHIP'
    | 'MOD-ENTERPRISE-APPROACH'
    | 'MOD-ENTERPRISE-PORTFOLIO'
    | 'MOD-ENTERPRISE-ENTITY-ROUTES'
    | 'MOD-ENTERPRISE-QUALIFICATION'
    | 'MOD-IDEAS-FEATURED'
    | 'MOD-IDEAS-TOPIC-FILTERS'
    | 'MOD-IDEAS-FRAMEWORKS'
    | 'MOD-IDEAS-MIND-TRAP'
    | 'MOD-IDEAS-NEWSLETTER'
    | 'MOD-CULTURE-SELECTED-WORK'
    | 'MOD-CULTURE-PROJECT-CARDS'
    | 'MOD-CULTURE-ROLE-CREDIT'
    | 'MOD-CULTURE-OFFICIAL-MEDIA'
    | 'MOD-CULTURE-COLLABORATION'
    | 'MOD-IMPACT-FOCUS-AREAS'
    | 'MOD-IMPACT-INITIATIVES'
    | 'MOD-IMPACT-EVIDENCE'
    | 'MOD-IMPACT-PARTNERS'
    | 'MOD-IMPACT-GEOGRAPHY'
    | 'MOD-IMPACT-PARTICIPATION'
    | 'MOD-MEDIA-TOPICS'
    | 'MOD-MEDIA-BIOS'
    | 'MOD-MEDIA-SPEAKER-REEL'
    | 'MOD-MEDIA-CLIPS'
    | 'MOD-MEDIA-RECOGNITION'
    | 'MOD-MEDIA-PRESS-KIT'
    | 'MOD-MEDIA-INQUIRY-ROUTES'
    | 'MOD-CONNECT-INTENT-SELECTOR'
    | 'MOD-CONNECT-ROUTE-FORM'
    | 'MOD-CONNECT-PRIVACY-NOTICE'
    | 'MOD-CONNECT-ACKNOWLEDGEMENT'
    | 'MOD-ARTICLE-BODY'
    | 'MOD-ARTICLE-CONTEXT'
    | 'MOD-ARTICLE-RELATED'
    | 'MOD-ARTICLE-SUBSCRIBE'
    | 'MOD-ENTITY-CONTEXT'
    | 'MOD-ENTITY-STATUS'
    | 'MOD-ENTITY-EVIDENCE'
    | 'MOD-ENTITY-OFFICIAL'
    | 'MOD-ENTITY-RELATED'
    | 'MOD-PROJECT-CONTEXT'
    | 'MOD-PROJECT-CREDITS'
    | 'MOD-PROJECT-MEDIA'
    | 'MOD-PROJECT-OFFICIAL'
    | 'MOD-PROJECT-RELATED'
    | 'MOD-INITIATIVE-PURPOSE'
    | 'MOD-INITIATIVE-PARTNERS'
    | 'MOD-INITIATIVE-OUTCOMES'
    | 'MOD-INITIATIVE-PARTICIPATE'
    | 'MOD-INITIATIVE-RELATED'
    | 'MOD-SEARCH-INPUT'
    | 'MOD-SEARCH-RESULTS'
    | 'MOD-SEARCH-EMPTY'
    | 'MOD-PRIVACY-POLICY'
    | 'MOD-PRIVACY-CONTACT'
    | 'MOD-TERMS-POLICY'
    | 'MOD-ACCESSIBILITY-COMMITMENT'
    | 'MOD-ACCESSIBILITY-LIMITS'
    | 'MOD-ACCESSIBILITY-ASSISTANCE';
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  heading: string;
  body?: string | null;
  points?:
    | {
        label: string;
        detail?: string | null;
        /**
         * Link the claim that supports this point. Unlinked metrics are not publishable.
         */
        claim?: (string | null) | Claim;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'proof';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  /**
   * Stable MOD ID. Traces this module to the copy deck, CTA and QA records.
   */
  moduleId:
    | 'MOD-HOME-HERO'
    | 'MOD-HOME-KYYBA-FLAGSHIP'
    | 'MOD-HOME-LEADERSHIP-JOURNEY'
    | 'MOD-HOME-SELECTED-ENTERPRISE'
    | 'MOD-HOME-SELECTED-IDEAS'
    | 'MOD-HOME-SELECTED-CULTURE'
    | 'MOD-HOME-SELECTED-IMPACT'
    | 'MOD-HOME-MEDIA-CREDIBILITY'
    | 'MOD-HOME-FINAL-CTA'
    | 'MOD-ABOUT-BIO'
    | 'MOD-ABOUT-TIMELINE'
    | 'MOD-ABOUT-PRINCIPLES'
    | 'MOD-ABOUT-RECOGNITION'
    | 'MOD-ABOUT-HUMAN-CONTEXT'
    | 'MOD-ABOUT-ENTERPRISE-BRIDGE'
    | 'MOD-ENTERPRISE-KYYBA-FLAGSHIP'
    | 'MOD-ENTERPRISE-APPROACH'
    | 'MOD-ENTERPRISE-PORTFOLIO'
    | 'MOD-ENTERPRISE-ENTITY-ROUTES'
    | 'MOD-ENTERPRISE-QUALIFICATION'
    | 'MOD-IDEAS-FEATURED'
    | 'MOD-IDEAS-TOPIC-FILTERS'
    | 'MOD-IDEAS-FRAMEWORKS'
    | 'MOD-IDEAS-MIND-TRAP'
    | 'MOD-IDEAS-NEWSLETTER'
    | 'MOD-CULTURE-SELECTED-WORK'
    | 'MOD-CULTURE-PROJECT-CARDS'
    | 'MOD-CULTURE-ROLE-CREDIT'
    | 'MOD-CULTURE-OFFICIAL-MEDIA'
    | 'MOD-CULTURE-COLLABORATION'
    | 'MOD-IMPACT-FOCUS-AREAS'
    | 'MOD-IMPACT-INITIATIVES'
    | 'MOD-IMPACT-EVIDENCE'
    | 'MOD-IMPACT-PARTNERS'
    | 'MOD-IMPACT-GEOGRAPHY'
    | 'MOD-IMPACT-PARTICIPATION'
    | 'MOD-MEDIA-TOPICS'
    | 'MOD-MEDIA-BIOS'
    | 'MOD-MEDIA-SPEAKER-REEL'
    | 'MOD-MEDIA-CLIPS'
    | 'MOD-MEDIA-RECOGNITION'
    | 'MOD-MEDIA-PRESS-KIT'
    | 'MOD-MEDIA-INQUIRY-ROUTES'
    | 'MOD-CONNECT-INTENT-SELECTOR'
    | 'MOD-CONNECT-ROUTE-FORM'
    | 'MOD-CONNECT-PRIVACY-NOTICE'
    | 'MOD-CONNECT-ACKNOWLEDGEMENT'
    | 'MOD-ARTICLE-BODY'
    | 'MOD-ARTICLE-CONTEXT'
    | 'MOD-ARTICLE-RELATED'
    | 'MOD-ARTICLE-SUBSCRIBE'
    | 'MOD-ENTITY-CONTEXT'
    | 'MOD-ENTITY-STATUS'
    | 'MOD-ENTITY-EVIDENCE'
    | 'MOD-ENTITY-OFFICIAL'
    | 'MOD-ENTITY-RELATED'
    | 'MOD-PROJECT-CONTEXT'
    | 'MOD-PROJECT-CREDITS'
    | 'MOD-PROJECT-MEDIA'
    | 'MOD-PROJECT-OFFICIAL'
    | 'MOD-PROJECT-RELATED'
    | 'MOD-INITIATIVE-PURPOSE'
    | 'MOD-INITIATIVE-PARTNERS'
    | 'MOD-INITIATIVE-OUTCOMES'
    | 'MOD-INITIATIVE-PARTICIPATE'
    | 'MOD-INITIATIVE-RELATED'
    | 'MOD-SEARCH-INPUT'
    | 'MOD-SEARCH-RESULTS'
    | 'MOD-SEARCH-EMPTY'
    | 'MOD-PRIVACY-POLICY'
    | 'MOD-PRIVACY-CONTACT'
    | 'MOD-TERMS-POLICY'
    | 'MOD-ACCESSIBILITY-COMMITMENT'
    | 'MOD-ACCESSIBILITY-LIMITS'
    | 'MOD-ACCESSIBILITY-ASSISTANCE';
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  heading: string;
  entries?:
    | {
        period: string;
        title: string;
        detail?: string | null;
        roleStatus: 'current' | 'former' | 'unresolved';
        claim?: (string | null) | Claim;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  /**
   * Stable MOD ID. Traces this module to the copy deck, CTA and QA records.
   */
  moduleId:
    | 'MOD-HOME-HERO'
    | 'MOD-HOME-KYYBA-FLAGSHIP'
    | 'MOD-HOME-LEADERSHIP-JOURNEY'
    | 'MOD-HOME-SELECTED-ENTERPRISE'
    | 'MOD-HOME-SELECTED-IDEAS'
    | 'MOD-HOME-SELECTED-CULTURE'
    | 'MOD-HOME-SELECTED-IMPACT'
    | 'MOD-HOME-MEDIA-CREDIBILITY'
    | 'MOD-HOME-FINAL-CTA'
    | 'MOD-ABOUT-BIO'
    | 'MOD-ABOUT-TIMELINE'
    | 'MOD-ABOUT-PRINCIPLES'
    | 'MOD-ABOUT-RECOGNITION'
    | 'MOD-ABOUT-HUMAN-CONTEXT'
    | 'MOD-ABOUT-ENTERPRISE-BRIDGE'
    | 'MOD-ENTERPRISE-KYYBA-FLAGSHIP'
    | 'MOD-ENTERPRISE-APPROACH'
    | 'MOD-ENTERPRISE-PORTFOLIO'
    | 'MOD-ENTERPRISE-ENTITY-ROUTES'
    | 'MOD-ENTERPRISE-QUALIFICATION'
    | 'MOD-IDEAS-FEATURED'
    | 'MOD-IDEAS-TOPIC-FILTERS'
    | 'MOD-IDEAS-FRAMEWORKS'
    | 'MOD-IDEAS-MIND-TRAP'
    | 'MOD-IDEAS-NEWSLETTER'
    | 'MOD-CULTURE-SELECTED-WORK'
    | 'MOD-CULTURE-PROJECT-CARDS'
    | 'MOD-CULTURE-ROLE-CREDIT'
    | 'MOD-CULTURE-OFFICIAL-MEDIA'
    | 'MOD-CULTURE-COLLABORATION'
    | 'MOD-IMPACT-FOCUS-AREAS'
    | 'MOD-IMPACT-INITIATIVES'
    | 'MOD-IMPACT-EVIDENCE'
    | 'MOD-IMPACT-PARTNERS'
    | 'MOD-IMPACT-GEOGRAPHY'
    | 'MOD-IMPACT-PARTICIPATION'
    | 'MOD-MEDIA-TOPICS'
    | 'MOD-MEDIA-BIOS'
    | 'MOD-MEDIA-SPEAKER-REEL'
    | 'MOD-MEDIA-CLIPS'
    | 'MOD-MEDIA-RECOGNITION'
    | 'MOD-MEDIA-PRESS-KIT'
    | 'MOD-MEDIA-INQUIRY-ROUTES'
    | 'MOD-CONNECT-INTENT-SELECTOR'
    | 'MOD-CONNECT-ROUTE-FORM'
    | 'MOD-CONNECT-PRIVACY-NOTICE'
    | 'MOD-CONNECT-ACKNOWLEDGEMENT'
    | 'MOD-ARTICLE-BODY'
    | 'MOD-ARTICLE-CONTEXT'
    | 'MOD-ARTICLE-RELATED'
    | 'MOD-ARTICLE-SUBSCRIBE'
    | 'MOD-ENTITY-CONTEXT'
    | 'MOD-ENTITY-STATUS'
    | 'MOD-ENTITY-EVIDENCE'
    | 'MOD-ENTITY-OFFICIAL'
    | 'MOD-ENTITY-RELATED'
    | 'MOD-PROJECT-CONTEXT'
    | 'MOD-PROJECT-CREDITS'
    | 'MOD-PROJECT-MEDIA'
    | 'MOD-PROJECT-OFFICIAL'
    | 'MOD-PROJECT-RELATED'
    | 'MOD-INITIATIVE-PURPOSE'
    | 'MOD-INITIATIVE-PARTNERS'
    | 'MOD-INITIATIVE-OUTCOMES'
    | 'MOD-INITIATIVE-PARTICIPATE'
    | 'MOD-INITIATIVE-RELATED'
    | 'MOD-SEARCH-INPUT'
    | 'MOD-SEARCH-RESULTS'
    | 'MOD-SEARCH-EMPTY'
    | 'MOD-PRIVACY-POLICY'
    | 'MOD-PRIVACY-CONTACT'
    | 'MOD-TERMS-POLICY'
    | 'MOD-ACCESSIBILITY-COMMITMENT'
    | 'MOD-ACCESSIBILITY-LIMITS'
    | 'MOD-ACCESSIBILITY-ASSISTANCE';
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  heading: string;
  intro?: string | null;
  source?: ('entities' | 'projects' | 'initiatives' | 'articles') | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * Stable MOD ID. Traces this module to the copy deck, CTA and QA records.
   */
  moduleId:
    | 'MOD-HOME-HERO'
    | 'MOD-HOME-KYYBA-FLAGSHIP'
    | 'MOD-HOME-LEADERSHIP-JOURNEY'
    | 'MOD-HOME-SELECTED-ENTERPRISE'
    | 'MOD-HOME-SELECTED-IDEAS'
    | 'MOD-HOME-SELECTED-CULTURE'
    | 'MOD-HOME-SELECTED-IMPACT'
    | 'MOD-HOME-MEDIA-CREDIBILITY'
    | 'MOD-HOME-FINAL-CTA'
    | 'MOD-ABOUT-BIO'
    | 'MOD-ABOUT-TIMELINE'
    | 'MOD-ABOUT-PRINCIPLES'
    | 'MOD-ABOUT-RECOGNITION'
    | 'MOD-ABOUT-HUMAN-CONTEXT'
    | 'MOD-ABOUT-ENTERPRISE-BRIDGE'
    | 'MOD-ENTERPRISE-KYYBA-FLAGSHIP'
    | 'MOD-ENTERPRISE-APPROACH'
    | 'MOD-ENTERPRISE-PORTFOLIO'
    | 'MOD-ENTERPRISE-ENTITY-ROUTES'
    | 'MOD-ENTERPRISE-QUALIFICATION'
    | 'MOD-IDEAS-FEATURED'
    | 'MOD-IDEAS-TOPIC-FILTERS'
    | 'MOD-IDEAS-FRAMEWORKS'
    | 'MOD-IDEAS-MIND-TRAP'
    | 'MOD-IDEAS-NEWSLETTER'
    | 'MOD-CULTURE-SELECTED-WORK'
    | 'MOD-CULTURE-PROJECT-CARDS'
    | 'MOD-CULTURE-ROLE-CREDIT'
    | 'MOD-CULTURE-OFFICIAL-MEDIA'
    | 'MOD-CULTURE-COLLABORATION'
    | 'MOD-IMPACT-FOCUS-AREAS'
    | 'MOD-IMPACT-INITIATIVES'
    | 'MOD-IMPACT-EVIDENCE'
    | 'MOD-IMPACT-PARTNERS'
    | 'MOD-IMPACT-GEOGRAPHY'
    | 'MOD-IMPACT-PARTICIPATION'
    | 'MOD-MEDIA-TOPICS'
    | 'MOD-MEDIA-BIOS'
    | 'MOD-MEDIA-SPEAKER-REEL'
    | 'MOD-MEDIA-CLIPS'
    | 'MOD-MEDIA-RECOGNITION'
    | 'MOD-MEDIA-PRESS-KIT'
    | 'MOD-MEDIA-INQUIRY-ROUTES'
    | 'MOD-CONNECT-INTENT-SELECTOR'
    | 'MOD-CONNECT-ROUTE-FORM'
    | 'MOD-CONNECT-PRIVACY-NOTICE'
    | 'MOD-CONNECT-ACKNOWLEDGEMENT'
    | 'MOD-ARTICLE-BODY'
    | 'MOD-ARTICLE-CONTEXT'
    | 'MOD-ARTICLE-RELATED'
    | 'MOD-ARTICLE-SUBSCRIBE'
    | 'MOD-ENTITY-CONTEXT'
    | 'MOD-ENTITY-STATUS'
    | 'MOD-ENTITY-EVIDENCE'
    | 'MOD-ENTITY-OFFICIAL'
    | 'MOD-ENTITY-RELATED'
    | 'MOD-PROJECT-CONTEXT'
    | 'MOD-PROJECT-CREDITS'
    | 'MOD-PROJECT-MEDIA'
    | 'MOD-PROJECT-OFFICIAL'
    | 'MOD-PROJECT-RELATED'
    | 'MOD-INITIATIVE-PURPOSE'
    | 'MOD-INITIATIVE-PARTNERS'
    | 'MOD-INITIATIVE-OUTCOMES'
    | 'MOD-INITIATIVE-PARTICIPATE'
    | 'MOD-INITIATIVE-RELATED'
    | 'MOD-SEARCH-INPUT'
    | 'MOD-SEARCH-RESULTS'
    | 'MOD-SEARCH-EMPTY'
    | 'MOD-PRIVACY-POLICY'
    | 'MOD-PRIVACY-CONTACT'
    | 'MOD-TERMS-POLICY'
    | 'MOD-ACCESSIBILITY-COMMITMENT'
    | 'MOD-ACCESSIBILITY-LIMITS'
    | 'MOD-ACCESSIBILITY-ASSISTANCE';
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  ctaId: string;
  heading: string;
  body?: string | null;
  label: string;
  destinationType: 'internal' | 'inquiry' | 'external' | 'download' | 'subscribe';
  destination: string;
  emphasis?: ('primary' | 'secondary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaModule';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  /**
   * Stable MOD ID. Traces this module to the copy deck, CTA and QA records.
   */
  moduleId:
    | 'MOD-HOME-HERO'
    | 'MOD-HOME-KYYBA-FLAGSHIP'
    | 'MOD-HOME-LEADERSHIP-JOURNEY'
    | 'MOD-HOME-SELECTED-ENTERPRISE'
    | 'MOD-HOME-SELECTED-IDEAS'
    | 'MOD-HOME-SELECTED-CULTURE'
    | 'MOD-HOME-SELECTED-IMPACT'
    | 'MOD-HOME-MEDIA-CREDIBILITY'
    | 'MOD-HOME-FINAL-CTA'
    | 'MOD-ABOUT-BIO'
    | 'MOD-ABOUT-TIMELINE'
    | 'MOD-ABOUT-PRINCIPLES'
    | 'MOD-ABOUT-RECOGNITION'
    | 'MOD-ABOUT-HUMAN-CONTEXT'
    | 'MOD-ABOUT-ENTERPRISE-BRIDGE'
    | 'MOD-ENTERPRISE-KYYBA-FLAGSHIP'
    | 'MOD-ENTERPRISE-APPROACH'
    | 'MOD-ENTERPRISE-PORTFOLIO'
    | 'MOD-ENTERPRISE-ENTITY-ROUTES'
    | 'MOD-ENTERPRISE-QUALIFICATION'
    | 'MOD-IDEAS-FEATURED'
    | 'MOD-IDEAS-TOPIC-FILTERS'
    | 'MOD-IDEAS-FRAMEWORKS'
    | 'MOD-IDEAS-MIND-TRAP'
    | 'MOD-IDEAS-NEWSLETTER'
    | 'MOD-CULTURE-SELECTED-WORK'
    | 'MOD-CULTURE-PROJECT-CARDS'
    | 'MOD-CULTURE-ROLE-CREDIT'
    | 'MOD-CULTURE-OFFICIAL-MEDIA'
    | 'MOD-CULTURE-COLLABORATION'
    | 'MOD-IMPACT-FOCUS-AREAS'
    | 'MOD-IMPACT-INITIATIVES'
    | 'MOD-IMPACT-EVIDENCE'
    | 'MOD-IMPACT-PARTNERS'
    | 'MOD-IMPACT-GEOGRAPHY'
    | 'MOD-IMPACT-PARTICIPATION'
    | 'MOD-MEDIA-TOPICS'
    | 'MOD-MEDIA-BIOS'
    | 'MOD-MEDIA-SPEAKER-REEL'
    | 'MOD-MEDIA-CLIPS'
    | 'MOD-MEDIA-RECOGNITION'
    | 'MOD-MEDIA-PRESS-KIT'
    | 'MOD-MEDIA-INQUIRY-ROUTES'
    | 'MOD-CONNECT-INTENT-SELECTOR'
    | 'MOD-CONNECT-ROUTE-FORM'
    | 'MOD-CONNECT-PRIVACY-NOTICE'
    | 'MOD-CONNECT-ACKNOWLEDGEMENT'
    | 'MOD-ARTICLE-BODY'
    | 'MOD-ARTICLE-CONTEXT'
    | 'MOD-ARTICLE-RELATED'
    | 'MOD-ARTICLE-SUBSCRIBE'
    | 'MOD-ENTITY-CONTEXT'
    | 'MOD-ENTITY-STATUS'
    | 'MOD-ENTITY-EVIDENCE'
    | 'MOD-ENTITY-OFFICIAL'
    | 'MOD-ENTITY-RELATED'
    | 'MOD-PROJECT-CONTEXT'
    | 'MOD-PROJECT-CREDITS'
    | 'MOD-PROJECT-MEDIA'
    | 'MOD-PROJECT-OFFICIAL'
    | 'MOD-PROJECT-RELATED'
    | 'MOD-INITIATIVE-PURPOSE'
    | 'MOD-INITIATIVE-PARTNERS'
    | 'MOD-INITIATIVE-OUTCOMES'
    | 'MOD-INITIATIVE-PARTICIPATE'
    | 'MOD-INITIATIVE-RELATED'
    | 'MOD-SEARCH-INPUT'
    | 'MOD-SEARCH-RESULTS'
    | 'MOD-SEARCH-EMPTY'
    | 'MOD-PRIVACY-POLICY'
    | 'MOD-PRIVACY-CONTACT'
    | 'MOD-TERMS-POLICY'
    | 'MOD-ACCESSIBILITY-COMMITMENT'
    | 'MOD-ACCESSIBILITY-LIMITS'
    | 'MOD-ACCESSIBILITY-ASSISTANCE';
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  heading: string;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  topic: 'enterprise' | 'leadership' | 'investing' | 'mind-trap' | 'culture' | 'impact';
  isFramework?: boolean | null;
  /**
   * Authorship must be settled before publication (Section 6, Ideas).
   */
  authorshipStatus: 'authored' | 'co-authored' | 'unresolved';
  publishedDate?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (string | null) | Asset;
  related?: (string | Article)[] | null;
  seo?: {
    /**
     * SEO record ID, e.g. SEO-HOME.
     */
    seoId?: string | null;
    /**
     * Unique page title. Required before an indexable page can be accepted.
     */
    title?: string | null;
    /**
     * Unique meta description.
     */
    description?: string | null;
    /**
     * Exclude from indexation. Forced on for search results and any non-production origin regardless of this value.
     */
    noindex?: boolean | null;
    /**
     * Rights-cleared 1200x630 social image. Subject to the same asset gate.
     */
    ogImage?: (string | null) | Asset;
  };
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  /**
   * Accountable role for this record. Roles, not named individuals — names are a G0 dependency.
   */
  ownerRole: string;
  /**
   * Traceability notes: source document, change request ID, or the reason a module deviates.
   */
  baselineNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities".
 */
export interface Entity {
  id: string;
  name: string;
  slug: string;
  /**
   * Kyyba is the flagship enterprise proof. Other work extends the narrative rather than competing with it.
   */
  isFlagship?: boolean | null;
  relationshipStatus: 'current' | 'former' | 'unresolved';
  /**
   * Exact approved public wording for the relationship. No inferred titles or implied ownership.
   */
  relationshipWording?: string | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Official destination. Validated as http(s) before it is rendered as an outbound link.
   */
  officialUrl?: string | null;
  logo?: (string | null) | Asset;
  displayOrder?: number | null;
  seo?: {
    /**
     * SEO record ID, e.g. SEO-HOME.
     */
    seoId?: string | null;
    /**
     * Unique page title. Required before an indexable page can be accepted.
     */
    title?: string | null;
    /**
     * Unique meta description.
     */
    description?: string | null;
    /**
     * Exclude from indexation. Forced on for search results and any non-production origin regardless of this value.
     */
    noindex?: boolean | null;
    /**
     * Rights-cleared 1200x630 social image. Subject to the same asset gate.
     */
    ogImage?: (string | null) | Asset;
  };
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  /**
   * Accountable role for this record. Roles, not named individuals — names are a G0 dependency.
   */
  ownerRole: string;
  /**
   * Traceability notes: source document, change request ID, or the reason a module deviates.
   */
  baselineNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  slug: string;
  creditStatus: 'verified' | 'unresolved';
  /**
   * Exact screen credit wording. No inferred producer or distribution role.
   */
  creditWording?: string | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  runtimeMinutes?: number | null;
  releaseYear?: number | null;
  /**
   * Official viewing destination.
   */
  officialUrl?: string | null;
  keyArt?: (string | null) | Asset;
  displayOrder?: number | null;
  seo?: {
    /**
     * SEO record ID, e.g. SEO-HOME.
     */
    seoId?: string | null;
    /**
     * Unique page title. Required before an indexable page can be accepted.
     */
    title?: string | null;
    /**
     * Unique meta description.
     */
    description?: string | null;
    /**
     * Exclude from indexation. Forced on for search results and any non-production origin regardless of this value.
     */
    noindex?: boolean | null;
    /**
     * Rights-cleared 1200x630 social image. Subject to the same asset gate.
     */
    ogImage?: (string | null) | Asset;
  };
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  /**
   * Accountable role for this record. Roles, not named individuals — names are a G0 dependency.
   */
  ownerRole: string;
  /**
   * Traceability notes: source document, change request ID, or the reason a module deviates.
   */
  baselineNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiatives".
 */
export interface Initiative {
  id: string;
  title: string;
  slug: string;
  legalStatus: 'registered' | 'program' | 'unresolved';
  focusArea?: string | null;
  geography?: string | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Every outcome figure needs a claim with an auditable methodology. No cumulative implication without proof.
   */
  outcomes?:
    | {
        measure: string;
        methodologyNote: string;
        claim: string | Claim;
        id?: string | null;
      }[]
    | null;
  partners?:
    | {
        name: string;
        /**
         * Named partners require permission before they appear publicly.
         */
        permissionOnFile?: boolean | null;
        id?: string | null;
      }[]
    | null;
  participationCriteria?: string | null;
  displayOrder?: number | null;
  seo?: {
    /**
     * SEO record ID, e.g. SEO-HOME.
     */
    seoId?: string | null;
    /**
     * Unique page title. Required before an indexable page can be accepted.
     */
    title?: string | null;
    /**
     * Unique meta description.
     */
    description?: string | null;
    /**
     * Exclude from indexation. Forced on for search results and any non-production origin regardless of this value.
     */
    noindex?: boolean | null;
    /**
     * Rights-cleared 1200x630 social image. Subject to the same asset gate.
     */
    ogImage?: (string | null) | Asset;
  };
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  /**
   * Accountable role for this record. Roles, not named individuals — names are a G0 dependency.
   */
  ownerRole: string;
  /**
   * Traceability notes: source document, change request ID, or the reason a module deviates.
   */
  baselineNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: string;
  title: string;
  /**
   * Stable asset ID used in the download analytics event.
   */
  downloadId: string;
  version: string;
  kind: 'bio' | 'press-kit' | 'one-sheet';
  /**
   * The downloadable file. Subject to the asset rights gate.
   */
  file?: (string | null) | Asset;
  /**
   * Accessible text equivalent of the download contents.
   */
  accessibleSummary: string;
  /**
   * Every material public claim on this record. Publication is blocked until each linked claim is Ready with approved wording and unexpired review date.
   */
  claims?: (string | Claim)[] | null;
  /**
   * Every published asset on this record. Publication is blocked until rights, credit, release and accessibility metadata are complete.
   */
  assets?: (string | Asset)[] | null;
  /**
   * Accountable role for this record. Roles, not named individuals — names are a G0 dependency.
   */
  ownerRole: string;
  /**
   * Traceability notes: source document, change request ID, or the reason a module deviates.
   */
  baselineNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The seven baseline routes. Route IDs, owner roles, SLAs and escalation criteria are fixed by the baseline; recipients and acceptance are operational configuration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-routes".
 */
export interface InquiryRoute {
  id: string;
  routeId: 'strategic-partnership' | 'investment-ma' | 'speaking' | 'media' | 'creative' | 'impact' | 'general';
  label: string;
  /**
   * Baseline owner role. Fixed by the baseline.
   */
  ownerRole: string;
  minimumQualification: string;
  /**
   * Baseline response window in hours.
   */
  slaHours: number;
  /**
   * OPEN OPERATIONAL DECISION: the baseline states hours but not whether they are elapsed or business hours. Configurable until decided.
   */
  slaClock: 'elapsed' | 'business';
  /**
   * Timezone the SLA clock uses. Confirm with the route owner.
   */
  slaTimezone?: string | null;
  /**
   * Primary owner mailbox. Unset in development; required before production acceptance.
   */
  primaryRecipient?: string | null;
  /**
   * Backup owner mailbox. Required before production acceptance.
   */
  backupRecipient?: string | null;
  acceptanceStatus: 'unassigned' | 'assigned' | 'accepted';
  /**
   * Who acknowledged, recorded verbatim. Do not infer.
   */
  acceptedBy?: string | null;
  acceptedAt?: string | null;
  escalationCriterion: string;
  /**
   * General inquiries never escalate to Tel; they are reclassified to the correct owner. SLA breach alone never escalates to Tel on any route.
   */
  escalatesToTel?: boolean | null;
  /**
   * A disabled route is hidden from the intent selector and rejects submissions.
   */
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  /**
   * Operational reference shown to the sender. Distinct from any analytics identifier.
   */
  reference: string;
  /**
   * Prevents a retried submission from creating a duplicate lead.
   */
  idempotencyKey?: string | null;
  route: 'strategic-partnership' | 'investment-ma' | 'speaking' | 'media' | 'creative' | 'impact' | 'general';
  fullName: string;
  email: string;
  /**
   * Route-specific qualification answers, validated server-side against the route schema.
   */
  qualification?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Delivery to the owner. A database insert alone is never "delivered".
   */
  deliveryState: 'stored' | 'pending' | 'delivered' | 'failed';
  /**
   * Owner-side progress. Provider acceptance is NOT acknowledgement and NOT a response.
   */
  workState: 'new' | 'acknowledged' | 'responded' | 'closed' | 'reclassified';
  slaDueAt?: string | null;
  acknowledgedAt?: string | null;
  respondedAt?: string | null;
  escalatedAt?: string | null;
  /**
   * Why this was escalated. SLA breach alone is not an escalation reason.
   */
  escalationReason?: string | null;
  /**
   * Validated attribution captured at submission (FR-UTM-01). Consent-aware.
   */
  attribution?: {
    sourcePage?: string | null;
    entryPage?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    /**
     * Recorded honestly. Consent denial is never silently replaced with invented attribution.
     */
    attributionState?: ('attributed' | 'unattributed' | 'consent-denied') | null;
  };
  consent: {
    privacyAccepted: boolean;
    policyVersion: string;
    consentedAt: string;
    analyticsConsent?: boolean | null;
    /**
     * Separate, explicit opt-in. Submitting an inquiry never subscribes anyone.
     */
    marketingOptIn?: boolean | null;
  };
  /**
   * Owner working notes. Not returned by any public endpoint.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-attempts".
 */
export interface DeliveryAttempt {
  id: string;
  inquiry: string | Inquiry;
  route: string;
  recipientKind: 'primary' | 'backup' | 'sender-ack';
  recipient: string;
  /**
   * "Sent" means the transport accepted the message. It does NOT mean a recipient read it. Bounces reconcile separately.
   */
  state: 'queued' | 'in-flight' | 'sent' | 'failed' | 'dead';
  attemptCount: number;
  maxAttempts: number;
  nextAttemptAt?: string | null;
  /**
   * Redacted transport error. Inquiry bodies are never logged here.
   */
  lastError?: string | null;
  providerMessageId?: string | null;
  sentAt?: string | null;
  /**
   * Reconciled from provider receipts, separately from internal acknowledgement.
   */
  bounceState?: ('none' | 'soft' | 'hard') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions".
 */
export interface NewsletterSubscription {
  id: string;
  email: string;
  state: 'pending-confirmation' | 'subscribed' | 'unsubscribed';
  /**
   * Single-use token for the confirmation link.
   */
  confirmationToken?: string | null;
  confirmationExpiresAt?: string | null;
  confirmationSentAt?: string | null;
  /**
   * Provider receipt proving transport acceptance.
   */
  confirmationMessageId?: string | null;
  consentedAt: string;
  policyVersion: string;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * Inventoried legacy path, verified to have existed. Do not invent old routes.
   */
  fromPath: string;
  decision: 'undecided' | '301' | '302' | '410';
  toPath?: string | null;
  /**
   * How this legacy URL was confirmed to exist (crawl, log, sitemap).
   */
  evidence?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-buckets".
 */
export interface RateLimitBucket {
  id: string;
  key: string;
  count: number;
  windowStart: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: string;
  event: string;
  subjectCollection?: string | null;
  subjectId?: string | null;
  /**
   * Role or system process. Not an end-visitor identifier.
   */
  actor?: string | null;
  detail?: string | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * A user may hold several explicit roles. Least privilege applies.
   */
  roles: ('administrator' | 'editor' | 'evidence-reviewer' | 'publisher' | 'route-owner' | 'qa')[];
  /**
   * Inquiry routes this route owner may see and work. Empty means no inquiry access.
   */
  assignedRoutes?:
    | ('strategic-partnership' | 'investment-ma' | 'speaking' | 'media' | 'creative' | 'impact' | 'general')[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'entities';
        value: string | Entity;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'initiatives';
        value: string | Initiative;
      } | null)
    | ({
        relationTo: 'downloads';
        value: string | Download;
      } | null)
    | ({
        relationTo: 'claims';
        value: string | Claim;
      } | null)
    | ({
        relationTo: 'evidence-sources';
        value: string | EvidenceSource;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'inquiry-routes';
        value: string | InquiryRoute;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'delivery-attempts';
        value: string | DeliveryAttempt;
      } | null)
    | ({
        relationTo: 'newsletter-subscriptions';
        value: string | NewsletterSubscription;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'rate-limit-buckets';
        value: string | RateLimitBucket;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: string | AuditEvent;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  pageId?: T;
  path?: T;
  purpose?: T;
  modules?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        proof?: T | ProofBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        ctaModule?: T | CtaBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
      };
  primaryCta?:
    | T
    | {
        ctaId?: T;
        label?: T;
        destinationType?: T;
        destination?: T;
      };
  seo?:
    | T
    | {
        seoId?: T;
        title?: T;
        description?: T;
        noindex?: T;
        ogImage?: T;
      };
  claims?: T;
  assets?: T;
  ownerRole?: T;
  baselineNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  moduleId?: T;
  claims?: T;
  assets?: T;
  eyebrow?: T;
  heading?: T;
  statement?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  moduleId?: T;
  claims?: T;
  assets?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProofBlock_select".
 */
export interface ProofBlockSelect<T extends boolean = true> {
  moduleId?: T;
  claims?: T;
  assets?: T;
  heading?: T;
  body?: T;
  points?:
    | T
    | {
        label?: T;
        detail?: T;
        claim?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  moduleId?: T;
  claims?: T;
  assets?: T;
  heading?: T;
  entries?:
    | T
    | {
        period?: T;
        title?: T;
        detail?: T;
        roleStatus?: T;
        claim?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  moduleId?: T;
  claims?: T;
  assets?: T;
  heading?: T;
  intro?: T;
  source?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  moduleId?: T;
  claims?: T;
  assets?: T;
  ctaId?: T;
  heading?: T;
  body?: T;
  label?: T;
  destinationType?: T;
  destination?: T;
  emphasis?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  moduleId?: T;
  claims?: T;
  assets?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  topic?: T;
  isFramework?: T;
  authorshipStatus?: T;
  publishedDate?: T;
  body?: T;
  heroImage?: T;
  related?: T;
  seo?:
    | T
    | {
        seoId?: T;
        title?: T;
        description?: T;
        noindex?: T;
        ogImage?: T;
      };
  claims?: T;
  assets?: T;
  ownerRole?: T;
  baselineNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entities_select".
 */
export interface EntitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isFlagship?: T;
  relationshipStatus?: T;
  relationshipWording?: T;
  summary?: T;
  body?: T;
  officialUrl?: T;
  logo?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        seoId?: T;
        title?: T;
        description?: T;
        noindex?: T;
        ogImage?: T;
      };
  claims?: T;
  assets?: T;
  ownerRole?: T;
  baselineNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  creditStatus?: T;
  creditWording?: T;
  summary?: T;
  body?: T;
  runtimeMinutes?: T;
  releaseYear?: T;
  officialUrl?: T;
  keyArt?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        seoId?: T;
        title?: T;
        description?: T;
        noindex?: T;
        ogImage?: T;
      };
  claims?: T;
  assets?: T;
  ownerRole?: T;
  baselineNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiatives_select".
 */
export interface InitiativesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  legalStatus?: T;
  focusArea?: T;
  geography?: T;
  summary?: T;
  body?: T;
  outcomes?:
    | T
    | {
        measure?: T;
        methodologyNote?: T;
        claim?: T;
        id?: T;
      };
  partners?:
    | T
    | {
        name?: T;
        permissionOnFile?: T;
        id?: T;
      };
  participationCriteria?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        seoId?: T;
        title?: T;
        description?: T;
        noindex?: T;
        ogImage?: T;
      };
  claims?: T;
  assets?: T;
  ownerRole?: T;
  baselineNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  downloadId?: T;
  version?: T;
  kind?: T;
  file?: T;
  accessibleSummary?: T;
  claims?: T;
  assets?: T;
  ownerRole?: T;
  baselineNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  claimId?: T;
  exactWording?: T;
  qualifier?: T;
  riskLevel?: T;
  verificationOwnerRole?: T;
  riskReviewerRole?: T;
  sources?: T;
  status?: T;
  approvedWording?: T;
  approvalDate?: T;
  reviewDate?: T;
  blockingReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-sources_select".
 */
export interface EvidenceSourcesSelect<T extends boolean = true> {
  title?: T;
  sourceType?: T;
  strength?: T;
  dated?: T;
  reference?: T;
  notes?: T;
  withdrawn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  assetId?: T;
  alt?: T;
  decorative?: T;
  rightsStatus?: T;
  source?: T;
  permittedUsage?: T;
  rightsExpiry?: T;
  creditRequired?: T;
  credit?: T;
  releaseRequired?: T;
  releaseOnFile?: T;
  captionsOrTranscript?: T;
  version?: T;
  developmentPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        social?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-routes_select".
 */
export interface InquiryRoutesSelect<T extends boolean = true> {
  routeId?: T;
  label?: T;
  ownerRole?: T;
  minimumQualification?: T;
  slaHours?: T;
  slaClock?: T;
  slaTimezone?: T;
  primaryRecipient?: T;
  backupRecipient?: T;
  acceptanceStatus?: T;
  acceptedBy?: T;
  acceptedAt?: T;
  escalationCriterion?: T;
  escalatesToTel?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  reference?: T;
  idempotencyKey?: T;
  route?: T;
  fullName?: T;
  email?: T;
  qualification?: T;
  deliveryState?: T;
  workState?: T;
  slaDueAt?: T;
  acknowledgedAt?: T;
  respondedAt?: T;
  escalatedAt?: T;
  escalationReason?: T;
  attribution?:
    | T
    | {
        sourcePage?: T;
        entryPage?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        attributionState?: T;
      };
  consent?:
    | T
    | {
        privacyAccepted?: T;
        policyVersion?: T;
        consentedAt?: T;
        analyticsConsent?: T;
        marketingOptIn?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-attempts_select".
 */
export interface DeliveryAttemptsSelect<T extends boolean = true> {
  inquiry?: T;
  route?: T;
  recipientKind?: T;
  recipient?: T;
  state?: T;
  attemptCount?: T;
  maxAttempts?: T;
  nextAttemptAt?: T;
  lastError?: T;
  providerMessageId?: T;
  sentAt?: T;
  bounceState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
  email?: T;
  state?: T;
  confirmationToken?: T;
  confirmationExpiresAt?: T;
  confirmationSentAt?: T;
  confirmationMessageId?: T;
  consentedAt?: T;
  policyVersion?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  decision?: T;
  toPath?: T;
  evidence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-buckets_select".
 */
export interface RateLimitBucketsSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  windowStart?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  event?: T;
  subjectCollection?: T;
  subjectId?: T;
  actor?: T;
  detail?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  assignedRoutes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  /**
   * Approved positioning. Changing this is a Class A strategic decision requiring Tel approval.
   */
  positioningLine: string;
  masterStatement: string;
  /**
   * Verified production origin used for absolute canonicals. UNSET until the domain decision is made (Appendix C). Canonicals are suppressed while unset rather than guessed.
   */
  productionOrigin?: string | null;
  /**
   * Master indexation switch. Defaults OFF so staging is private and noindex. Turned on only at launch authorization.
   */
  allowIndexing?: boolean | null;
  /**
   * Version stamped onto every consent record. Stays "draft-unapproved" until the privacy reviewer signs off.
   */
  privacyPolicyVersion: string;
  analytics?: {
    /**
     * Optional. Analytics stays inert until this is configured AND consent is granted.
     */
    ga4MeasurementId?: string | null;
    enabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  /**
   * Approved primary navigation: About | Enterprise & Investments | Ideas | Film & Culture | Impact | Media & Speaking | Connect.
   */
  primary: {
    label: string;
    path: string;
    pageId: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Grouped footer navigation.
   */
  groups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              path: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * VERIFIED destinations only. An unverified social profile is left out rather than guessed (Section 5).
   */
  socialLinks?:
    | {
        platform: string;
        url: string;
        /**
         * Unverified links are not rendered.
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legalLine?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  positioningLine?: T;
  masterStatement?: T;
  productionOrigin?: T;
  allowIndexing?: T;
  privacyPolicyVersion?: T;
  analytics?:
    | T
    | {
        ga4MeasurementId?: T;
        enabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        path?: T;
        pageId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              path?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        verified?: T;
        id?: T;
      };
  legalLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}